---
- name: Set K3s TLS SAN argument
  ansible.builtin.set_fact:
    k3s_tls_san_arg_effective: "{{ k3s_tls_san_arg | default('') }}"

- name: Install K3s on control-plane init node
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_EXEC: "server --cluster-init {{ k3s_tls_san_arg_effective }}"
  when:
    - k3s_control_node | bool
    - k3s_cluster_init | default(false) | bool

- name: Install K3s on control-plane join nodes
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_EXEC: "server --server https://{{ k3s_api_endpoint }}:6443 {{ k3s_tls_san_arg_effective }}"
  when:
    - k3s_control_node | bool
    - not (k3s_cluster_init | default(false) | bool)

- name: Install K3s on worker nodes
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_EXEC: "agent --server https://{{ k3s_api_endpoint }}:6443"
  when: not (k3s_control_node | bool)
